version: '2'
services:
    testnewsvc-app:
        image: testnewsvc
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://testnewsvc-postgresql:5432/testnewsvc
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    testnewsvc-postgresql:
        extends:
            file: postgresql.yml
            service: testnewsvc-postgresql
